[QTOOL - 593] - Create an integrated system to run codegen & perf tests.
In test/hexagon we can now do
$> make all.
This runs.
     1. codegen tests i.e. check-codegen.
     2. apps test i.e. tests for performance.
     3. gathers performance numbers i.e. bmark-report.

Also, I have commented out 4 tests in varith.cpp that will be re-enabled once
bug 20163 is fixed. This patch also modifiles median to not process borders like
the arch team baseline. To process borders, add -DBORDERS to the compilations flags
used to compile median.cpp

Change-Id: Ied404d3a6f04212256be7442aa018bde9aa22c12
Reviewed-on: https://review-hexagon.quicinc.com/32541
Reviewed-by: Ron Lieberman <ronl@quicinc.com>
Tested-by: Ron Lieberman <ronl@quicinc.com>

diff --git a/test/hexagon/apps/gaussian3x3_update_functions/Makefile b/test/hexagon/apps/gaussian3x3_update_functions/Makefile
--- a/test/hexagon/apps/gaussian3x3_update_functions/Makefile
+++ b/test/hexagon/apps/gaussian3x3_update_functions/Makefile
@@ -21,7 +21,7 @@ gaussian3x3.out: gaussian3x3_run.o gaussian3x3.o gaussian3x3.h
 all: gaussian3x3.out
 
 clean:
-	rm -rf *.o gaussian3x3.h *~ *.out *.bc *.ll *.s *.txt pmu* *.html *.iss.0 pa_dump.core.0 stats_dump.v60.iss.0 out.bin result; \
+	rm -rf *.o gaussian3x3.h *~ *.out *.bc *.ll *.s *.txt pmu* *.html *.iss.0 pa_dump.core.0 stats_dump.v60.iss.0 out.bin result run.std*; \
         $(MAKE) -C ref clean
 
 .PHONY: assembly
@@ -38,11 +38,24 @@ bitcode: gaussian3x3.cpp
 
 .PHONY: all
 
-all: gaussian3x3.out run
+all: gaussian3x3.out run bmark-report
+
+bmark-report:
+	if [ -a ${CURR_DIR}/run.stdout ]; then \
+		grep -q PASS ${CURR_DIR}/result; \
+		if [ $$? -eq 0 ];  then \
+			grep "cycles/pixel" ${CURR_DIR}/run.stdout | awk '{print $$6"("$$4"):",$$7 " cycles/pixel"}'; \
+		else \
+			echo "${TEST_NAME}: FAIL";\
+		fi \
+	else \
+		echo "run.stdout not found; please run make run first"; \
+	fi
+
 
 
 run: gaussian3x3.out
-	${HEX_TOOLS}/bin/hexagon-sim gaussian3x3.out --timing -- 1920 1080 ${HALIDE_TOP}/test/hexagon/apps/testvectors/football1920x1080.bin out.bin; \
+	${HEX_TOOLS}/bin/hexagon-sim gaussian3x3.out --timing -- 1920 1080 ${HALIDE_TOP}/test/hexagon/apps/testvectors/football1920x1080.bin out.bin 1>${CURR_DIR}/run.stdout 2>${CURR_DIR}/run.stderr; \
 	RUN_STATUS=$$?; \
 	FAIL=0; \
 	if [ $$RUN_STATUS -ne 0 ]; then \
diff --git a/test/hexagon/apps/median/Makefile b/test/hexagon/apps/median/Makefile
--- a/test/hexagon/apps/median/Makefile
+++ b/test/hexagon/apps/median/Makefile
@@ -6,7 +6,7 @@ HEXAGON_CLANG=${HEX_TOOLS}/bin/hexagon-clang++
 CLANG_CPP=/pkg/qct/software/llvm/build_tools/llvm34_140306/bin/clang++
 LDFLAGS=-L/pkg/qct/software/llvm/build_tools/libc++_140306/lib -L/pkg/qct/software/llvm/build_tools/libedit_tw/lib -L ${HALIDE_TOP}/bin -Wl,--start-group -lHalide -lpthread -ldl  -lc++ -Wl,--end-group
 INCLUDES=-I${HALIDE_TOP}/include -I${HALIDE_TOP}/test/hexagon/include -I/pkg/qct/software/llvm/build_tools/libc++_140306/include/c++/v1
-
+TEST_NAME= $(shell basename ${CURR_DIR})
 B128_MODE=
 GDB=
 
@@ -24,7 +24,7 @@ median.out: median_run.o median.o median.h
 all: median.out
 
 clean:
-	rm -rf *.o median.h *~ *.out *.bc *.ll *.s *.txt pmu* *.html *.iss.0 out.bin result
+	rm -rf *.o median.h *~ *.out *.bc *.ll *.s *.txt pmu* *.html *.iss.0 out.bin result run.std* pa_dump.core.0 stats_dump.v60.iss.0
 
 .PHONY: assembly
 
@@ -38,13 +38,23 @@ bitcode: median.cpp
 	${CLANG_CPP}  median.cpp -g  -lHalide -lpthread -ldl -o median.generate.out -O0 -DBITCODE --std=c++11 ${INCLUDES} ${LDFLAGS}; \
 	export LD_LIBRARY_PATH=${HALIDE_TOP}/bin:${LD_LIBRARY_PATH}; ./median.generate.out ${B128_MODE}
 
-.PHONY: all
+.PHONY: all run bmark-report
 
-all: median.out run
-
+all: median.out run bmark-report
+bmark-report:
+	if [ -a ${CURR_DIR}/run.stdout ]; then \
+		grep -q PASS ${CURR_DIR}/result; \
+		if [ $$? -eq 0 ];  then \
+			grep "cycles/pixel" ${CURR_DIR}/run.stdout | awk '{print $$6"("$$4"):",$$7 " cycles/pixel"}'; \
+		else \
+			echo "${TEST_NAME}: FAIL";\
+		fi \
+	else \
+		echo "run.stdout not found; please run make run first"; \
+	fi
 
 run: median.out
-	${HEX_TOOLS}/bin/hexagon-sim median.out --timing -- 1920 1080 ${HALIDE_TOP}/test/hexagon/apps/testvectors/football1920x1080.bin out.bin; \
+	${HEX_TOOLS}/bin/hexagon-sim median.out --timing -- 1920 1080 ${HALIDE_TOP}/test/hexagon/apps/testvectors/football1920x1080.bin out.bin 1>${CURR_DIR}/run.stdout 2>${CURR_DIR}/run.stderr; \
 	RUN_STATUS=$$?; \
 	FAIL=0; \
 	if [ $$RUN_STATUS -ne 0 ]; then \
@@ -56,7 +66,7 @@ run: median.out
 	if [ $$FAIL -eq 0 ]; then \
           echo PASS > ${CURR_DIR}/result; \
 	  echo PASS; \
-        else \
+	else \
           echo FAIL > ${CURR_DIR}/result; \
 	  echo FAIL;\
         fi
