[QTOOL-2519] Make hexagon/apps exit on failure
- updated test Makefiles to return with non-zero status on failure
- updated hexagon/apps/Makefile to check for error return
  - added KNOWNFAIL - Tests currently known to fail (failures ignored)
  - added KEEPGOING - Keep going on unknown failures (if set to non-zero)

Change-Id: Iae43cb954064098b511f3a5bc788952c25230899
Reviewed-on: https://review-hexagon.quicinc.com/42330
Tested-by: Anshu Das Gupta <adasgupt@quicinc.com>
Reviewed-by: Ron Lieberman <ronl@quicinc.com>

diff --git a/test/hexagon/apps/Makefile b/test/hexagon/apps/Makefile
--- a/test/hexagon/apps/Makefile
+++ b/test/hexagon/apps/Makefile
@@ -3,7 +3,8 @@ CC = /pkg/qct/software/gnu64/gcc/4.8.2/bin/g++
 CXXFLAGS = "--std=c++11"
 CLANG = hexagon-clang++
 
-SUBDIRS = median \
+SUBDIRS = \
+  median \
   gaussian3x3_update_functions \
   sobel \
   integrate \
@@ -20,8 +21,13 @@ NOT_READY4PRIMTIME = \
   epsilon \
   fast9
 
-# Causes make error  camera_pipe
+# Tests currently known to fail (failures ignored)
+KNOWNFAIL = \
+  integrate \
+  sigma3x3
 
+# Keep going on unknown failures (if set to non-zero)
+KEEPGOING=0
 
 .PHONY: all run perf bmark-report
 
@@ -31,6 +37,21 @@ run:
 	for dir in $(SUBDIRS); do \
 		export MALLOC_CHECK_=0; \
 		$(MAKE) -C $$dir clean run; \
+		if [ $$? -ne 0 ];  then \
+		  IGNORE=$(KEEPGOING); \
+		  for chk in $(KNOWNFAIL); do \
+		    if [ "$$dir" = "$$chk" ]; then \
+		      echo "KNOWNFAIL"; \
+		      echo "Warning: non-zero exit status, but ignoring knownfail"; \
+		      IGNORE=1; \
+		    fi; \
+		  done; \
+		  if [ "$$IGNORE" -eq 0 ];  then \
+		    echo "FAIL"; \
+		    echo "Error: non-zero exit status"; \
+		    exit 1; \
+		  fi; \
+		fi \
 	done
 
 clean:
@@ -50,5 +71,20 @@ not-ready:
 	for dir in $(NOT_READY4PRIMTIME); do \
 		export MALLOC_CHECK_=0; \
 		$(MAKE) -C $$dir TIMING=  EXTRA_FLAGS=-DNOVECTOR clean run; \
+		if [ $$? -ne 0 ];  then \
+		  IGNORE=$(KEEPGOING); \
+		  for chk in $(KNOWNFAIL); do \
+		    if [ "$$dir" = "$$chk" ]; then \
+		      echo "KNOWNFAIL"; \
+		      echo "Warning: non-zero exit status, but ignoring knownfail"; \
+		      IGNORE=1; \
+		    fi; \
+		  done; \
+		  if [ "$$IGNORE" -eq 0 ];  then \
+		    echo "FAIL"; \
+		    echo "Error: non-zero exit status"; \
+		    exit 1; \
+		  fi; \
+		fi \
 	done
 
