[QTOOL - 594] - Convert sobel to use a real image as input.
Use football1920x1080 as input to sobel. The synthetic testcase
fails right now. I will fix it later. The real test passes and checks
out against the golden output file.

Change-Id: I8b54703bc3a95e3756255f41ab709d106f724058
Reviewed-on: https://review-hexagon.quicinc.com/32568
Reviewed-by: Ron Lieberman <ronl@quicinc.com>
Tested-by: Ron Lieberman <ronl@quicinc.com>

diff --git a/test/hexagon/apps/sobel/Makefile b/test/hexagon/apps/sobel/Makefile
--- a/test/hexagon/apps/sobel/Makefile
+++ b/test/hexagon/apps/sobel/Makefile
@@ -1,52 +1,94 @@
-
-HALIDE_TOP = `pwd`/../../../..
-CC=/pkg/qct/software/gnu64/gcc/4.8.2/bin/g++
+CURR_DIR = $(shell pwd)
+HALIDE_TOP = ${CURR_DIR}/../../../..
+CXXFLAGS="--std=c++11"
+HEXAGON_CLANG=${HEX_TOOLS}/bin/hexagon-clang++
+CLANG_CPP=/pkg/qct/software/llvm/build_tools/llvm34_140306/bin/clang++
+LDFLAGS=-L/pkg/qct/software/llvm/build_tools/libc++_140306/lib -L/pkg/qct/software/llvm/build_tools/libedit_tw/lib -L ${HALIDE_TOP}/bin -Wl,--start-group -lHalide -lpthread -ldl  -lc++ -Wl,--end-group
+INCLUDES=-I${HALIDE_TOP}/include -I${HALIDE_TOP}/test/hexagon/include -I/pkg/qct/software/llvm/build_tools/libc++_140306/include/c++/v1
 CXXFLAGS="--std=c++11"
 
 
 sobel.o sobel.h: sobel.cpp
-	${CC} sobel.cpp -g -I ${HALIDE_TOP}/include -L ${HALIDE_TOP}/bin -lHalide -lpthread -ldl -o sobel.generate.out -O0 -DRUN -I ${HALIDE_TOP}/test/hexagon/include ${CXXFLAGS}
+	${CLANG_CPP} sobel.cpp -g  -o sobel.generate.out -O0 -DRUN  ${INCLUDES} ${LDFLAGS} ${CXXFLAGS}
 	export LD_LIBRARY_PATH=${HALIDE_TOP}/bin:$LD_LIBRARY_PATH
 	./sobel.generate.out
 
 
 sobel_run.o: sobel.o sobel.h sobel_run.cpp
-	${CLANG} -c sobel_run.cpp -mhvx -mv60 -I ${HALIDE_TOP}/include -O0 -g -I ${HALIDE_TOP}/test/hexagon/include
+	${HEXAGON_CLANG} -c sobel_run.cpp -mhvx -mv60 -I ${HALIDE_TOP}/include -O0 -g -I ${HALIDE_TOP}/test/hexagon/include
 
 sobel.out: sobel_run.o sobel.o sobel.h
 	${HEX_TOOLS}/bin/hexagon-link -march=hexagon -mcpu=hexagonv60 -o sobel.out ${HEX_TOOLS}/target/hexagon/lib/v60/crt0_standalone.o ${HEX_TOOLS}/target/hexagon/lib/v60/crt0.o ${HEX_TOOLS}/target/hexagon/lib/v60/init.o -L${HEX_TOOLS}/target/hexagon/lib -L${HEX_TOOLS}/target/hexagon/lib/v60 sobel_run.o sobel.o --start-group -lstandalone -lc -lgcc -lhexagon --end-group ${HEX_TOOLS}/target/hexagon/lib/v60/fini.o
 
-all: sobel.out
-
 clean:
-	rm -rf *.o sobel.h *~ *.out *.bc *.ll *.s *.txt pmu* *.html
+	rm -rf *.o median.h *~ *.out *.bc *.ll *.s *.txt pmu* *.html *.iss.0 out.bin result run.std* pa_dump.core.0 stats_dump.v60.iss.0
 
 .PHONY: assembly
 
 assembly: sobel.cpp
-	${CC} sobel.cpp -g -I ${HALIDE_TOP}/include -L ${HALIDE_TOP}/bin -lHalide -lpthread -ldl -o sobel.generate.out -O0 -DASSEMBLY -I ${HALIDE_TOP}/test/hexagon/include ${CXXFLAGS}
+	${CLANG_CPP} sobel.cpp -g -o sobel.generate.out -O0 -DASSEMBLY ${INCLUDES} ${LDFLAGS} ${CXXFLAGS}
 	export LD_LIBRARY_PATH=${HALIDE_TOP}/bin:$LD_LIBRARY_PATH
 	./sobel.generate.out
 
 .PHONY: bitcode
 
 bitcode: sobel.cpp
-	${CC} sobel.cpp -g -I ${HALIDE_TOP}/include -L ${HALIDE_TOP}/bin -lHalide -lpthread -ldl -o sobel.generate.out -O0 -DBITCODE -I ${HALIDE_TOP}/test/hexagon/include ${CXXFLAGS}
+	${CLANG_CPP} sobel.cpp -g  -o sobel.generate.out -O0 -DBITCODE ${INCLUDES} ${LDFLAGS} ${CXXFLAGS}
 	export LD_LIBRARY_PATH=${HALIDE_TOP}/bin:$LD_LIBRARY_PATH
 	./sobel.generate.out
 
 .PHONY: all
 
-all: sobel.out run
+all: sobel.out run bmark-report
 
+bmark-report:
+	if [ -a ${CURR_DIR}/run.stdout ]; then \
+		grep -q PASS ${CURR_DIR}/result; \
+		if [ $$? -eq 0 ];  then \
+			grep "cycles/pixel" ${CURR_DIR}/run.stdout | awk '{print $$6"("$$4"):",$$7 " cycles/pixel"}'; \
+		else \
+			echo "${TEST_NAME}: FAIL";\
+		fi \
+	else \
+		echo "run.stdout not found; please run make run first"; \
+	fi
 
 run: sobel.out
-	${HEX_TOOLS}/bin/hexagon-sim sobel.out --timing
+	${HEX_TOOLS}/bin/hexagon-sim sobel.out --timing -- 1920 1080 ${HALIDE_TOP}/test/hexagon/apps/testvectors/football1920x1080.bin out.bin 1>${CURR_DIR}/run.stdout 2>${CURR_DIR}/run.stderr; \
+	RUN_STATUS=$$?; \
+	FAIL=0; \
+	if [ $$RUN_STATUS -ne 0 ]; then \
+	  FAIL=1; \
+	fi; \
+	if ! cmp out.bin ${CURR_DIR}/golden_out.bin; then \
+          FAIL=1; \
+        fi; \
+	if [ $$FAIL -eq 0 ]; then \
+          echo PASS > ${CURR_DIR}/result; \
+	  echo PASS; \
+	else \
+          echo FAIL > ${CURR_DIR}/result; \
+	  echo FAIL;\
+        fi
+
 
 
 .PHONY: stmt
 
 stmt: sobel.cpp
-	${CC} sobel.cpp -g -I ${HALIDE_TOP}/include -L ${HALIDE_TOP}/bin -lHalide -lpthread -ldl -o sobel.generate.out -O0 -DSTMT -I ${HALIDE_TOP}/test/hexagon/include ${CXXFLAGS}
+	${CLANG_CPP} sobel.cpp -g  -o sobel.generate.out -O0 -DSTMT ${INCLUDES} ${LDFLAGS} ${CXXFLAGS}
 	export LD_LIBRARY_PATH=${HALIDE_TOP}/bin:$LD_LIBRARY_PATH
 	./sobel.generate.out
+
+.PHONY: synthetic
+
+sobel_run.synthetic.o: sobel.o sobel.h sobel_run.cpp
+	${HEXAGON_CLANG} -c sobel_run.cpp -mhvx -mv60 -I ${HALIDE_TOP}/include -O0 -g -I ${HALIDE_TOP}/test/hexagon/include -DSYNTHETIC -o sobel_run.synthetic.o ${CXXFLAGS}
+
+
+sobel.synthetic.out: sobel_run.synthetic.o sobel.o sobel.h
+	${HEX_TOOLS}/bin/hexagon-link -march=hexagon -mcpu=hexagonv60 -o sobel.synthetic.out ${HEX_TOOLS}/target/hexagon/lib/v60/crt0_standalone.o ${HEX_TOOLS}/target/hexagon/lib/v60/crt0.o ${HEX_TOOLS}/target/hexagon/lib/v60/init.o -L${HEX_TOOLS}/target/hexagon/lib -L${HEX_TOOLS}/target/hexagon/lib/v60 sobel_run.synthetic.o sobel.o --start-group -lstandalone -lc -lgcc -lhexagon --end-group ${HEX_TOOLS}/target/hexagon/lib/v60/fini.o
+
+
+synthetic: sobel.synthetic.out
+	${HEX_TOOLS}/bin/hexagon-sim sobel.synthetic.out --timing
